### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by R3verseCha0s** [NYAN-x-CAT/Lime-Downloader#1]
I would like to request one feature. like you have on your RAT it would be nice to add an option to use a pastebin link in the downloader so we can easily change the link its downloading from. It should be easy enough

**Comment by NYAN-x-CAT** [comment]
Are trying to say that you want to add a downloader feature into LimeRAT?

**Comment by R3verseCha0s** [comment]
No. I mean in the downloader instead of putting links in the box it should take only one pastebin link. So we can change the download link right from pastebin.

**Comment by NYAN-x-CAT** [comment]
I see, I already have a new update but it's not 100% complete yet. I may add this feature.

**Comment by R3verseCha0s** [comment]
It would be nice especially if you want to constantly update your client.
